### ISSUE TITLE
Whitepaper: Distinction and visualisation of Ecosystems, Data Spaces and Data Infrastructure

### ISSUE THREAD

**Issue by tob921013** [eclipse-edc/Publications#15]
To help non-experts on data spaces as well as more knowledgeable interested parties to understand dataspaces and to further distinct them from terms like "ecosystem" and "data infrastructure", a visual distinction might be helpful (see below). 

![image](https://user-images.githubusercontent.com/98738524/153160864-8f8de9be-2e1f-4b57-9b20-fddc7315d32e.png)

**Comment by PeterKoen-MSFT** [comment]
The model pictured in this graphic is outdated and I would prefer to not include it in the official documentation. Especially because it references a specific dataspace which is only one possible implementation of the concept of a dataspace.
Also the term "Gaia-X compliant IDS System" is misleading as this term currently isn't defined. 
An explanation of concepts and terms is highly welcome, but it needs to represent the current conceptual thinking of dataspaces.
